[tool.ruff]
# Global settings
line-length = 100
target-version = "py311"
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist",
]

# Linting settings
[tool.ruff.lint]
select = ["E", "F", "I", "N", "B", "A", "C4", "UP", "ANN", "RUF"]
ignore = []

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]  # Ignore imported but unused in __init__.py files

[tool.ruff.lint.isort]
known-first-party = ["lib"]

[tool.ruff.format]
# Like Black, use double quotes for strings
quote-style = "double"
# Indent with 4 spaces
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false